name: Metrics
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Chiloven945
          filename: metrics.svg
          template: classic
          base: header, activity, repositories
          config_timezone: Asia/Chongqing

          # ğŸ—“ï¸ Isometric commit calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # ğŸˆ·ï¸ Languages activity
          plugin_languages: yes

          # ğŸ“° Recent activity
          plugin_activity: yes

          # ğŸ“Œ Starred topics
          plugin_topics: yes
          plugin_topics_mode: labels
          plugin_topics_sort: random

          # ğŸ­ Comment reactions
          plugin_reactions: yes
          
          # ğŸ§‘â€ğŸ¤â€ğŸ§‘ People
          plugin_people: yes

          # ğŸ¼ Music activity and suggestions
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT }}"
          plugin_music_user: 31aagy6vodynowvbf5uzlpopjvwq
          plugin_music_mode: recent
          plugin_music_limit: 5

          # ğŸ—¼ Rss feed
          plugin_rss: yes
          plugin_rss_source: "https://chiloven.top/index.xml"
          plugin_rss_limit: 3

          # ğŸ•¹ï¸ Steam
          plugin_steam: yes
          plugin_steam_token: "${{ secrets.STEAM_TOKEN}}"
          plugin_steam_user: "76561199202785847"
          





