name: Metrics
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-card:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Core GitHub metrics (github.svg)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_SECRET }}
          filename: github.svg

          user: Chiloven945
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Asia/Chongqing

          # ğŸ—“ï¸ Isometric commit calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # ğŸˆ·ï¸ Languages activity
          plugin_languages: yes

          # ğŸ­ Comment reactions
          plugin_reactions: yes

          # ğŸ§‘â€ğŸ¤â€ğŸ§‘ People
          plugin_people: yes

  social-card:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Social feeds (social.svg)
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: social.svg

          user: Chiloven945
          base: ""
          base_skip: yes
          config_timezone: Asia/Chongqing

          # ğŸ¼ Music (Spotify)
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_CLIENT }}
          plugin_music_user: 31aagy6vodynowvbf5uzlpopjvwq
          plugin_music_mode: recent
          plugin_music_limit: 5

          # ğŸ—¼ RSS
          plugin_rss: yes
          plugin_rss_source: https://chiloven.top/index.xml
          plugin_rss_limit: 3

          # ğŸ•¹ï¸ Steam
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: "76561199202785847"
          plugin_steam_sections: player, most-played, recently-played
          plugin_steam_games_limit: 3
          plugin_steam_recent_games_limit: 2
